#!/usr/bin/env python3
"""Build a curated single-file context bundle for web ChatGPT review."""

from __future__ import annotations

import subprocess
from datetime import datetime, timezone
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
OUTPUT_RELATIVE_PATH = Path("docs/gpt_context.md")

ENTRYPOINT_FILES = [
    Path("README_FOR_GPT.md"),
    Path("AGENTS.md"),
    Path("README.md"),
    Path("main.tex"),
]

TEXT_GLOBS = [
    "sections/*.tex",
    "tables/*.tex",
    "docs/figure_guidelines.md",
    "figures/README.md",
    "notes/*.md",
    "references.bib",
]

BINARY_GLOBS = [
    "figures/*.pdf",
    "figures/*.png",
    "figures/*.svg",
    "main.pdf",
]


def run_git(root: Path, args: list[str]) -> str:
    try:
        completed = subprocess.run(
            ["git", *args],
            cwd=root,
            check=True,
            stdout=subprocess.PIPE,
            stderr=subprocess.PIPE,
            text=True,
        )
    except (FileNotFoundError, subprocess.CalledProcessError):
        return "Git unavailable or uninitialized"

    output = completed.stdout.strip()
    return output if output else "(empty)"


def detect_language(path: Path) -> str:
    suffix = path.suffix.lower()
    if suffix == ".tex":
        return "tex"
    if suffix == ".bib":
        return "bibtex"
    if suffix == ".py":
        return "python"
    if suffix == ".md":
        return "markdown"
    return "text"


def collect_text_files(root: Path) -> list[Path]:
    output_path = root / OUTPUT_RELATIVE_PATH
    collected: list[Path] = []
    seen: set[Path] = set()

    def add(path: Path) -> None:
        if not path.exists() or not path.is_file():
            return
        resolved = path.resolve()
        if resolved == output_path.resolve() or resolved in seen:
            return
        seen.add(resolved)
        collected.append(path)

    for relative_path in ENTRYPOINT_FILES:
        add(root / relative_path)

    for pattern in TEXT_GLOBS:
        for path in sorted(root.glob(pattern)):
            add(path)

    return collected


def collect_binary_artifacts(root: Path) -> list[Path]:
    artifacts: list[Path] = []
    seen: set[Path] = set()
    for pattern in BINARY_GLOBS:
        for path in sorted(root.glob(pattern)):
            if not path.is_file():
                continue
            resolved = path.resolve()
            if resolved in seen:
                continue
            seen.add(resolved)
            artifacts.append(path)
    return artifacts


def format_file_block(root: Path, path: Path) -> str:
    relative_path = path.relative_to(root).as_posix()
    language = detect_language(path)
    content = path.read_text(encoding="utf-8")
    return "\n".join(
        [
            f"## File: {relative_path}",
            "",
            f"```{language}",
            content.rstrip(),
            "```",
            "",
        ]
    )


def format_binary_index(root: Path) -> str:
    artifacts = collect_binary_artifacts(root)
    if not artifacts:
        return "No binary figure or PDF artifacts found.\n"

    lines = []
    for path in artifacts:
        relative_path = path.relative_to(root).as_posix()
        size = path.stat().st_size
        lines.append(f"- `{relative_path}` ({size:,} bytes)")
    return "\n".join(lines) + "\n"


def build_context(root: Path = ROOT) -> str:
    root = root.resolve()
    generated_at = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M:%S UTC")
    commit = run_git(root, ["rev-parse", "--short", "HEAD"])
    branch = run_git(root, ["branch", "--show-current"])
    status = run_git(root, ["status", "--short"])

    parts = [
        "# GPT Review Context",
        "",
        "This file is generated by `scripts/build_gpt_context.py`.",
        "Use it as the first-read bundle for web ChatGPT review. Source files remain authoritative.",
        "",
        "## Snapshot",
        "",
        f"- Generated at: {generated_at}",
        f"- Git branch: {branch}",
        f"- Git commit: {commit}",
        "",
        "## Git Status",
        "",
        "```text",
        status,
        "```",
        "",
        "## Binary Artifact Index",
        "",
        format_binary_index(root).rstrip(),
        "",
        "# Selected Text Sources",
        "",
    ]

    for path in collect_text_files(root):
        parts.append(format_file_block(root, path).rstrip())
        parts.append("")

    return "\n".join(parts).rstrip() + "\n"


def write_context(root: Path = ROOT) -> Path:
    root = root.resolve()
    output_path = root / OUTPUT_RELATIVE_PATH
    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(build_context(root), encoding="utf-8")
    return output_path


def main() -> None:
    output_path = write_context(ROOT)
    print(output_path.relative_to(ROOT).as_posix())


if __name__ == "__main__":
    main()
